### ISSUE TITLE
Make types accessible from other repositories

### ISSUE THREAD

**Issue by guilhermelimak** [perry-js/perry#41]
Right now we have no way to access the types on this repository from outside, to solve that I think we should move the types to a repository of their own and import it here and wherever else is needed.

We could also set up all repositories as a scoped monorepo and use lerna to manage it to make it a bit less painful.

**Comment by armand1m** [comment]
Hmmm this seems interesting. I think adding lerna is also proper, since we already have even a packages folder, we might be able to move the types to a specific package and publish it to npm separately also

**Comment by armand1m** [comment]
this is being addressed in #66

**Comment by armand1m** [comment]
https://github.com/perry-js/perry/tree/master/packages/perry-interfaces
https://github.com/perry-js/perry/tree/master/packages/types
